### ISSUE TITLE
Avoid overriding go-version in gobump

### ISSUE THREAD

**Issue by rawlingsj** [chainguard-dev/gobump#5]
Today we have a few places where we are overriding the go-version used by gobump, 

e.g.

https://github.com/search?q=repo%3Awolfi-dev%2Fos%20go-version&type=code

This is because the default is currently 1.20 
https://github.com/wolfi-dev/os/blob/a97e56a0f5e229a5703936ad4b075318f2b0f826/pipelines/go/bump.yaml#L17-L19

Wonder if we can come up with an approach to auto detect this in the pipeline or something else to avoid adding the extra go-version overrides?

**Comment by hectorj2f** [comment]
We are adding a functionality to internally run `go mod tidy` command as part of gobump. I'll handle this scenario to get the env go version and set it to the go mod file using the source code. That way we avoid to set it when defining the package.
